import { build } from 'esbuild';
import { writeFile, readFile, mkdir } from 'node:fs/promises';
import { JADE_CONTROL_METADATA } from './jade-control-metadata.js';
const design=await build({entryPoints:['design-workspace.js'],bundle:true,format:'iife',write:false,
  minify:true,charset:'ascii',target:'chrome100',loader:{'.md':'text','.css':'text'}});
const designJs=design.outputFiles[0].text.replaceAll('</script','<\\/script');
await mkdir('../artifacts/design-workspace',{recursive:true});
await writeFile('../artifacts/design-workspace/jade-ui-theme.css',await readFile('jade-ui-theme.css','utf8'));
await writeFile('../artifacts/design-workspace/index.html','<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jade设计</title></head><body><script>'+designJs+'</script></body></html>');
const designChunks=[];for(let p=0;p<designJs.length;p+=4096)designChunks.push(JSON.stringify(designJs.slice(p,p+4096)));
await writeFile('../src/DesignWorkspaceScript.h','#pragma once\n#include <string>\n// Generated by designer-tools/build.mjs.\ninline std::wstring DesignWorkspaceScript(){const char* chunks[]={'+designChunks.join(',\n')+'};std::wstring out;for(const char* c:chunks)while(*c)out+=static_cast<unsigned char>(*c++);return out;}\n');
const catalogEvents=[],catalogMethods=[];
for(const [kind,metadata] of Object.entries(JADE_CONTROL_METADATA)) {
  for(const event of metadata.events)catalogEvents.push(`{${[kind,event.label,event.code].map(JSON.stringify).join(',')}}`);
  catalogMethods.push(`{${JSON.stringify(kind)},${JSON.stringify((metadata.methods||[]).map(([name])=>name).join('、'))}}`);
}
await writeFile('../src/DesignerControlCatalog.h',`#pragma once
#include <string_view>
// Generated from jade-control-metadata.js by build.mjs.
namespace DesignerControlCatalog {
struct Event {std::string_view type,label,code;};
inline constexpr Event Events[]={${catalogEvents.join(',\n')}};
struct Methods {std::string_view type,names;};
inline constexpr Methods PublicMethods[]={${catalogMethods.join(',\n')}};
inline const Event* Find(std::string_view type,std::string_view code) {
  if(type=="list")type="super-list";
  for(const auto& event:Events)if(event.type==type&&event.code==code)return &event;
  return nullptr;
}
}
`);
const result = await build({ entryPoints: ['index.js'], bundle:true, format:'iife', write:false,
  minify:true, charset:'ascii', legalComments:'inline', target:'chrome100' });
const js=result.outputFiles[0].text;
if(js.includes(')JADETOOLS"')) throw new Error('Raw literal delimiter collision');
const chunks=[]; for(let p=0;p<js.length;p+=4096) chunks.push(JSON.stringify(js.slice(p,p+4096)));
await writeFile('../src/DesignerToolsScript.h', '#pragma once\n#include <string>\n// Generated by designer-tools/build.mjs; do not edit.\ninline std::wstring DesignerToolsScript() {\nconst char* chunks[]={\n'+chunks.join(',\n')+'\n};\nstd::wstring out; for(const char* chunk:chunks) while(*chunk) out+=static_cast<unsigned char>(*chunk++); return out;\n}\n');
const runtime=await build({entryPoints:['runtime-diagnostics.js'],bundle:true,format:'iife',write:false,minify:true,charset:'ascii',legalComments:'inline',target:'chrome100'});
const runtimeJs=runtime.outputFiles[0].text;
const runtimeChunks=[];for(let p=0;p<runtimeJs.length;p+=4096)runtimeChunks.push(JSON.stringify(runtimeJs.slice(p,p+4096)));
await writeFile('../src/RuntimeDiagnosticsScript.h','#pragma once\n#include <string>\n// Generated by designer-tools/build.mjs; do not edit.\ninline std::string RuntimeDiagnosticsScript(){\nconst char* chunks[]={\n'+runtimeChunks.join(',\n')+'\n};\nstd::string out;for(const char* chunk:chunks)out+=chunk;return out;\n}\n');
await writeFile('NOTICE.txt', 'Bundled libraries: parse5 (MIT), entities (BSD-2-Clause), lucide (ISC).\n\n'+
  await readFile('node_modules/parse5/LICENSE','utf8')+'\n'+await readFile('node_modules/entities/LICENSE','utf8')+'\n'+await readFile('node_modules/lucide/LICENSE','utf8'));
