import { build } from 'esbuild';
import { writeFile, readFile } from 'node:fs/promises';
const result = await build({ entryPoints: ['index.js'], bundle:true, format:'iife', write:false,
  minify:true, charset:'ascii', legalComments:'inline', target:'chrome100' });
const js=result.outputFiles[0].text;
if(js.includes(')JADETOOLS"')) throw new Error('Raw literal delimiter collision');
const chunks=[]; for(let p=0;p<js.length;p+=4096) chunks.push(JSON.stringify(js.slice(p,p+4096)));
await writeFile('../src/DesignerToolsScript.h', '#pragma once\n#include <string>\n// Generated by designer-tools/build.mjs; do not edit.\ninline std::wstring DesignerToolsScript() {\nconst char* chunks[]={\n'+chunks.join(',\n')+'\n};\nstd::wstring out; for(const char* chunk:chunks) while(*chunk) out+=static_cast<unsigned char>(*chunk++); return out;\n}\n');
const runtime=await build({entryPoints:['runtime-diagnostics.js'],bundle:true,format:'iife',write:false,minify:true,charset:'ascii',legalComments:'inline',target:'chrome100'});
const runtimeJs=runtime.outputFiles[0].text;
const runtimeChunks=[];for(let p=0;p<runtimeJs.length;p+=4096)runtimeChunks.push(JSON.stringify(runtimeJs.slice(p,p+4096)));
await writeFile('../src/RuntimeDiagnosticsScript.h','#pragma once\n#include <string>\n// Generated by designer-tools/build.mjs; do not edit.\ninline std::string RuntimeDiagnosticsScript(){\nconst char* chunks[]={\n'+runtimeChunks.join(',\n')+'\n};\nstd::string out;for(const char* chunk:chunks)out+=chunk;return out;\n}\n');
await writeFile('NOTICE.txt', 'Bundled libraries: parse5 (MIT), entities (BSD-2-Clause), lucide (ISC).\n\n'+
  await readFile('node_modules/parse5/LICENSE','utf8')+'\n'+await readFile('node_modules/entities/LICENSE','utf8')+'\n'+await readFile('node_modules/lucide/LICENSE','utf8'));
